name: Test artifact action
on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: Test Dataverse Action
    env:
      PORT: 8080
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: Run Dataverse Action
        id: dataverse
        uses: ./
        with:
          image_tag: "burritohasbeeneaten"
          postgresql_version: 15
          jvm_options: |
            dataverse.api.signature-secret=eikaizieb2Oghaex
            dataverse.pid.datacite.rest-api-url=https://api.datacite.org
      - name: Check artifact
        id: artifact-check
        if: ${{ failure(steps.dataverse) }}
        uses: xSAVIKx/artifact-exists-action@v0
        with:
          name: "logs.tgz"
      - name: Set GitHub Action as success if "dataverse" has failed
        if: ${{ success(steps.artifact-check) }}
        run: exit 0
